on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: mv template/.gitignore template/gitignore
      - run: mv .gitignore gitignore
      - run: mv template/.env.example template/.env.development
      - run: cp template/.env.development template/.env.production
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}